### PR TITLE
Added parser for ugly and/or negative hex, fixed Serpent types

### PR DESCRIPTION
**Pull request by tinybike**
I think this makes -abi work for all of the augur code (verifying that tonight).

### CODE REVIEW

**Comment by axic** [comment]
Thank you for the patch. I am submitting a PR to bn.js to support 0x prefixes, which makes this much cleaner.

Also it is weird that Serpent makes no distinction between string and bytes. Is string there ASCII?

**Comment by tinybike** [comment]
Well, it's really more like Serpent doesn't have a "string" type per se, it just has "bytes".  What I mean by that is, Serpent doesn't do any conversion for you; it expects hex-encoded byte strings.  A raw byte string just gets added as-is to the encoded data, but for utf-8 strings, augur-abi converts each character to its Unicode value (e.g. `hello world! -> 0x68656c6c6f20776f726c6421`) and this hex string is added to the encoded data.  As it happens, augur doesn't use byte strings for anything other than utf-8, so augur-abi can be nice and simple: if the parameter is string/bytes type, then it gets put through the `charCodeAt` grinder!

**Comment by axic** [comment]
@tinybike I've tried to find a reference to the *Serpent* notation, but can't seem to find one?

**Comment by tinybike** [comment]
@axic As I understand it, the Serpent notation is just https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI, using a subset of the available data types -- int256, int256[], and bytes.

**Comment by axic** [comment]
I am sorry it took this long. Part of this has been merged with #7. Working now on making handling variables (numbers) better.

**Comment by axic** [comment]
Number parsing is done, see c54a870739bdf3b2e1c80cffdac8a8672df8bf91

**Pull request closed without merging**
